name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Running Build Command...
    - name: Run a multi-line script
      run: npm run build
    - name: Azure Blob Storage Upload
      uses: bacongobbler/azure-blob-storage-upload@v1.0.0
      with:
        # The name of the directory you want to upload
        source_dir: ./dist
        # The name of the storage account container these assets will be uploaded to
        container_name: $web
        # The connection string for the storage account
        connection_string:  ${{ secrets.AZURE_STORAGE_CONNECTIONSTRING }}
